version: '3'
services:  
  sapi-archivos:
    image: pos-archivos
    build:
      context: .
      dockerfile: src/WebApi/DockerfileProd
    ports:
        - 8083:8080
    environment:
        - ASPNETCORE_ENVIRONMENT=Production
        - TZ=America/El_Salvador
    volumes:
        - /data/api-archivos:/media/archivos
